language: java

dist: bionic

jdk:
  openjdk11

services:
  - redis

before_script:
  - cp config/application.yml.test config/application-test.yml
  - wget https://repo.mysql.com/mysql-apt-config_0.8.15-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.15-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `onlinejudge` COLLATE `utf8_unicode_ci`;'

script:
  - mvn clean package test

after_success:
  - mvn jacoco:report
  - bash <(curl -s https://codecov.io/bash)
  - mvn sonar:sonar coveralls:report