spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.246.128:3306/lic?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hejianglll
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000

  redis:
    host: 192.168.246.128
    port: 6379
    password:
    max-total: 4
    max-idle: 4
    min-idle: 4
    max-wait-millis: 1000

  mail:
    host:
    port:
    username:
    password:

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    encoding:
      charset: UTF-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
lic:
  generator-fake-data: false
token:
  expire:
    seconds: 7200
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)
server:
  port: 8080